import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GalaxyBackground from './GalaxyBackground';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-gradient-to-br from-[#0f2027] via-[#2c5364] to-[#00eaff] min-h-screen relative`}> 
        <GalaxyBackground />
        <div className="flex min-h-screen relative z-10">
          {/* Sidebar for desktop */}
          <nav className="hidden md:flex flex-col w-64 shadow-2xl p-6 gap-6 glassmorphism bg-white/10">
            <a href="/" className="text-xl font-bold text-white hover:text-[#00eaff] transition">🏠 Home</a>
            <a href="/consult" className="text-xl font-bold text-white hover:text-[#00eaff] transition">💻 Consult</a>
            <a href="/services" className="text-xl font-bold text-white hover:text-[#00eaff] transition">🛎️ Services</a>
            <a href="/blogs" className="text-xl font-bold text-white hover:text-[#00eaff] transition">📝 Blogs</a>
            <a href="/feedback" className="text-xl font-bold text-white hover:text-[#00eaff] transition">⭐ Feedback</a>
          </nav>
          {/* Main content */}
          <main className="flex-1 flex flex-col">
            {children}
            {/* Bottom tab bar for mobile */}
            <nav className="fixed bottom-0 left-0 right-0 z-50 md:hidden flex justify-around items-center shadow-2xl py-2 glassmorphism bg-white/10">
              <a href="/" className="flex flex-col items-center text-xs text-white hover:text-[#00eaff] transition"><span className="text-2xl">🏠</span>Home</a>
              <a href="/consult" className="flex flex-col items-center text-xs text-white hover:text-[#00eaff] transition"><span className="text-2xl">💻</span>Consult</a>
              <a href="/services" className="flex flex-col items-center text-xs text-white hover:text-[#00eaff] transition"><span className="text-2xl">🛎️</span>Services</a>
              <a href="/blogs" className="flex flex-col items-center text-xs text-white hover:text-[#00eaff] transition"><span className="text-2xl">📝</span>Blogs</a>
              <a href="/feedback" className="flex flex-col items-center text-xs text-white hover:text-[#00eaff] transition"><span className="text-2xl">⭐</span>Feedback</a>
            </nav>
          </main>
        </div>
      
      </body>
    </html>
  );
}
